/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MapDetailDto
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiMapsResponse200 = {
  data: MapDetailDto[]
  status: 200
}

export type getApiMapsResponseSuccess = (getApiMapsResponse200) & {
  headers: Headers;
};
;

export type getApiMapsResponse = (getApiMapsResponseSuccess)

export const getGetApiMapsUrl = () => {




  return `/api/maps`
}

export const getApiMaps = async ( options?: RequestInit): Promise<getApiMapsResponse> => {

  const res = await fetch(getGetApiMapsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiMapsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiMapsResponse
}





export const getGetApiMapsQueryKey = () => {
    return [
    `/api/maps`
    ] as const;
    }


export const getGetApiMapsQueryOptions = <TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMaps>>> = ({ signal }) => getApiMaps({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMaps>>>
export type GetApiMapsQueryError = unknown


export function useGetApiMaps<TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMaps>>,
          TError,
          Awaited<ReturnType<typeof getApiMaps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMaps<TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMaps>>,
          TError,
          Awaited<ReturnType<typeof getApiMaps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMaps<TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMaps<TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiMapsMapIdResponse200 = {
  data: MapDetailDto
  status: 200
}

export type getApiMapsMapIdResponse404 = {
  data: void
  status: 404
}

export type getApiMapsMapIdResponseSuccess = (getApiMapsMapIdResponse200) & {
  headers: Headers;
};
export type getApiMapsMapIdResponseError = (getApiMapsMapIdResponse404) & {
  headers: Headers;
};

export type getApiMapsMapIdResponse = (getApiMapsMapIdResponseSuccess | getApiMapsMapIdResponseError)

export const getGetApiMapsMapIdUrl = (mapId: string,) => {




  return `/api/maps/${mapId}`
}

export const getApiMapsMapId = async (mapId: string, options?: RequestInit): Promise<getApiMapsMapIdResponse> => {

  const res = await fetch(getGetApiMapsMapIdUrl(mapId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiMapsMapIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiMapsMapIdResponse
}





export const getGetApiMapsMapIdQueryKey = (mapId: string,) => {
    return [
    `/api/maps/${mapId}`
    ] as const;
    }


export const getGetApiMapsMapIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapsMapIdQueryKey(mapId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMapsMapId>>> = ({ signal }) => getApiMapsMapId(mapId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapsMapIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMapsMapId>>>
export type GetApiMapsMapIdQueryError = void


export function useGetApiMapsMapId<TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(
 mapId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapsMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiMapsMapId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapsMapId<TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapsMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiMapsMapId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapsMapId<TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMapsMapId<TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapsMapIdQueryOptions(mapId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiMapsMapIdCoverResponse200 = {
  data: void
  status: 200
}

export type getApiMapsMapIdCoverResponse404 = {
  data: void
  status: 404
}

export type getApiMapsMapIdCoverResponseSuccess = (getApiMapsMapIdCoverResponse200) & {
  headers: Headers;
};
export type getApiMapsMapIdCoverResponseError = (getApiMapsMapIdCoverResponse404) & {
  headers: Headers;
};

export type getApiMapsMapIdCoverResponse = (getApiMapsMapIdCoverResponseSuccess | getApiMapsMapIdCoverResponseError)

export const getGetApiMapsMapIdCoverUrl = (mapId: string,) => {




  return `/api/maps/${mapId}/cover`
}

export const getApiMapsMapIdCover = async (mapId: string, options?: RequestInit): Promise<getApiMapsMapIdCoverResponse> => {

  const res = await fetch(getGetApiMapsMapIdCoverUrl(mapId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiMapsMapIdCoverResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiMapsMapIdCoverResponse
}





export const getGetApiMapsMapIdCoverQueryKey = (mapId: string,) => {
    return [
    `/api/maps/${mapId}/cover`
    ] as const;
    }


export const getGetApiMapsMapIdCoverQueryOptions = <TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapsMapIdCoverQueryKey(mapId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMapsMapIdCover>>> = ({ signal }) => getApiMapsMapIdCover(mapId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapsMapIdCoverQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMapsMapIdCover>>>
export type GetApiMapsMapIdCoverQueryError = void


export function useGetApiMapsMapIdCover<TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(
 mapId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapsMapIdCover>>,
          TError,
          Awaited<ReturnType<typeof getApiMapsMapIdCover>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapsMapIdCover<TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapsMapIdCover>>,
          TError,
          Awaited<ReturnType<typeof getApiMapsMapIdCover>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapsMapIdCover<TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMapsMapIdCover<TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapsMapIdCoverQueryOptions(mapId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






