/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiMapsParams,
  MapDetailDto,
  MapImportResultDto,
  PagedResultOfMapListItemDto,
  PostApiMapsImportBody
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiMapsResponse200 = {
  data: PagedResultOfMapListItemDto
  status: 200
}

export type getApiMapsResponseSuccess = (getApiMapsResponse200) & {
  headers: Headers;
};
;

export type getApiMapsResponse = (getApiMapsResponseSuccess)

export const getGetApiMapsUrl = (params?: GetApiMapsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/maps?${stringifiedParams}` : `/api/maps`
}

export const getApiMaps = async (params?: GetApiMapsParams, options?: RequestInit): Promise<getApiMapsResponse> => {

  const res = await fetch(getGetApiMapsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiMapsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiMapsResponse
}





export const getGetApiMapsQueryKey = (params?: GetApiMapsParams,) => {
    return [
    `/api/maps`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiMapsQueryOptions = <TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(params?: GetApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMaps>>> = ({ signal }) => getApiMaps(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMaps>>>
export type GetApiMapsQueryError = unknown


export function useGetApiMaps<TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(
 params: undefined |  GetApiMapsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMaps>>,
          TError,
          Awaited<ReturnType<typeof getApiMaps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMaps<TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(
 params?: GetApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMaps>>,
          TError,
          Awaited<ReturnType<typeof getApiMaps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMaps<TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(
 params?: GetApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMaps<TData = Awaited<ReturnType<typeof getApiMaps>>, TError = unknown>(
 params?: GetApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMaps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiMapsMapIdResponse200 = {
  data: MapDetailDto
  status: 200
}

export type getApiMapsMapIdResponse404 = {
  data: void
  status: 404
}

export type getApiMapsMapIdResponseSuccess = (getApiMapsMapIdResponse200) & {
  headers: Headers;
};
export type getApiMapsMapIdResponseError = (getApiMapsMapIdResponse404) & {
  headers: Headers;
};

export type getApiMapsMapIdResponse = (getApiMapsMapIdResponseSuccess | getApiMapsMapIdResponseError)

export const getGetApiMapsMapIdUrl = (mapId: string,) => {




  return `/api/maps/${mapId}`
}

export const getApiMapsMapId = async (mapId: string, options?: RequestInit): Promise<getApiMapsMapIdResponse> => {

  const res = await fetch(getGetApiMapsMapIdUrl(mapId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiMapsMapIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiMapsMapIdResponse
}





export const getGetApiMapsMapIdQueryKey = (mapId: string,) => {
    return [
    `/api/maps/${mapId}`
    ] as const;
    }


export const getGetApiMapsMapIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapsMapIdQueryKey(mapId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMapsMapId>>> = ({ signal }) => getApiMapsMapId(mapId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapsMapIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMapsMapId>>>
export type GetApiMapsMapIdQueryError = void


export function useGetApiMapsMapId<TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(
 mapId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapsMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiMapsMapId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapsMapId<TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapsMapId>>,
          TError,
          Awaited<ReturnType<typeof getApiMapsMapId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapsMapId<TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMapsMapId<TData = Awaited<ReturnType<typeof getApiMapsMapId>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapsMapIdQueryOptions(mapId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiMapsMapIdCoverResponse200 = {
  data: void
  status: 200
}

export type getApiMapsMapIdCoverResponse404 = {
  data: void
  status: 404
}

export type getApiMapsMapIdCoverResponseSuccess = (getApiMapsMapIdCoverResponse200) & {
  headers: Headers;
};
export type getApiMapsMapIdCoverResponseError = (getApiMapsMapIdCoverResponse404) & {
  headers: Headers;
};

export type getApiMapsMapIdCoverResponse = (getApiMapsMapIdCoverResponseSuccess | getApiMapsMapIdCoverResponseError)

export const getGetApiMapsMapIdCoverUrl = (mapId: string,) => {




  return `/api/maps/${mapId}/cover`
}

export const getGetApiMapsMapIdSongUrl = (mapId: string,) => {




  return `/api/maps/${mapId}/song`
}

export const getApiMapsMapIdCover = async (mapId: string, options?: RequestInit): Promise<getApiMapsMapIdCoverResponse> => {

  const res = await fetch(getGetApiMapsMapIdCoverUrl(mapId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiMapsMapIdCoverResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiMapsMapIdCoverResponse
}





export const getGetApiMapsMapIdCoverQueryKey = (mapId: string,) => {
    return [
    `/api/maps/${mapId}/cover`
    ] as const;
    }


export const getGetApiMapsMapIdCoverQueryOptions = <TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMapsMapIdCoverQueryKey(mapId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMapsMapIdCover>>> = ({ signal }) => getApiMapsMapIdCover(mapId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: mapId !== null && mapId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMapsMapIdCoverQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMapsMapIdCover>>>
export type GetApiMapsMapIdCoverQueryError = void


export function useGetApiMapsMapIdCover<TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(
 mapId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapsMapIdCover>>,
          TError,
          Awaited<ReturnType<typeof getApiMapsMapIdCover>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapsMapIdCover<TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMapsMapIdCover>>,
          TError,
          Awaited<ReturnType<typeof getApiMapsMapIdCover>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMapsMapIdCover<TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMapsMapIdCover<TData = Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError = void>(
 mapId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMapsMapIdCover>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMapsMapIdCoverQueryOptions(mapId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiMapsMapIdRefetchResponse202 = {
  data: void
  status: 202
}

export type postApiMapsMapIdRefetchResponse404 = {
  data: void
  status: 404
}

export type postApiMapsMapIdRefetchResponseSuccess = (postApiMapsMapIdRefetchResponse202) & {
  headers: Headers;
};
export type postApiMapsMapIdRefetchResponseError = (postApiMapsMapIdRefetchResponse404) & {
  headers: Headers;
};

export type postApiMapsMapIdRefetchResponse = (postApiMapsMapIdRefetchResponseSuccess | postApiMapsMapIdRefetchResponseError)

export const getPostApiMapsMapIdRefetchUrl = (mapId: string,) => {




  return `/api/maps/${mapId}/refetch`
}

export const postApiMapsMapIdRefetch = async (mapId: string, options?: RequestInit): Promise<postApiMapsMapIdRefetchResponse> => {

  const res = await fetch(getPostApiMapsMapIdRefetchUrl(mapId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiMapsMapIdRefetchResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiMapsMapIdRefetchResponse
}





export const getPostApiMapsMapIdRefetchMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMapsMapIdRefetch>>, TError,{mapId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMapsMapIdRefetch>>, TError,{mapId: string}, TContext> => {

const mutationKey = ['postApiMapsMapIdRefetch'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMapsMapIdRefetch>>, {mapId: string}> = (props) => {
          const {mapId} = props ?? {};

          return  postApiMapsMapIdRefetch(mapId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiMapsMapIdRefetchMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMapsMapIdRefetch>>>

    export type PostApiMapsMapIdRefetchMutationError = void

    export const usePostApiMapsMapIdRefetch = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMapsMapIdRefetch>>, TError,{mapId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMapsMapIdRefetch>>,
        TError,
        {mapId: string},
        TContext
      > => {
      return useMutation(getPostApiMapsMapIdRefetchMutationOptions(options), queryClient);
    }
    export type postApiMapsImportResponse200 = {
  data: MapImportResultDto
  status: 200
}

export type postApiMapsImportResponse400 = {
  data: void
  status: 400
}

export type postApiMapsImportResponse401 = {
  data: void
  status: 401
}

export type postApiMapsImportResponseSuccess = (postApiMapsImportResponse200) & {
  headers: Headers;
};
export type postApiMapsImportResponseError = (postApiMapsImportResponse400 | postApiMapsImportResponse401) & {
  headers: Headers;
};

export type postApiMapsImportResponse = (postApiMapsImportResponseSuccess | postApiMapsImportResponseError)

export const getPostApiMapsImportUrl = () => {




  return `/api/maps/import`
}

export const postApiMapsImport = async (postApiMapsImportBody: PostApiMapsImportBody, options?: RequestInit): Promise<postApiMapsImportResponse> => {
    const formData = new FormData();
if(postApiMapsImportBody.metadata !== undefined) {
 formData.append(`metadata`, postApiMapsImportBody.metadata);
 }

if(postApiMapsImportBody.cover !== undefined) {
 formData.append(`cover`, postApiMapsImportBody.cover);
 }

  const res = await fetch(getPostApiMapsImportUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiMapsImportResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiMapsImportResponse
}





export const getPostApiMapsImportMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMapsImport>>, TError,{data: PostApiMapsImportBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMapsImport>>, TError,{data: PostApiMapsImportBody}, TContext> => {

const mutationKey = ['postApiMapsImport'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMapsImport>>, {data: PostApiMapsImportBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiMapsImport(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiMapsImportMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMapsImport>>>
    export type PostApiMapsImportMutationBody = PostApiMapsImportBody
    export type PostApiMapsImportMutationError = void

    export const usePostApiMapsImport = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMapsImport>>, TError,{data: PostApiMapsImportBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMapsImport>>,
        TError,
        {data: PostApiMapsImportBody},
        TContext
      > => {
      return useMutation(getPostApiMapsImportMutationOptions(options), queryClient);
    }
    export type putApiMapsMapIdLikeResponse204 = {
  data: void
  status: 204
}

export type putApiMapsMapIdLikeResponse404 = {
  data: void
  status: 404
}

export type putApiMapsMapIdLikeResponseSuccess = (putApiMapsMapIdLikeResponse204) & {
  headers: Headers;
};
export type putApiMapsMapIdLikeResponseError = (putApiMapsMapIdLikeResponse404) & {
  headers: Headers;
};

export type putApiMapsMapIdLikeResponse = (putApiMapsMapIdLikeResponseSuccess | putApiMapsMapIdLikeResponseError)

export const getPutApiMapsMapIdLikeUrl = (mapId: string,) => {




  return `/api/maps/${mapId}/like`
}

export const putApiMapsMapIdLike = async (mapId: string, options?: RequestInit): Promise<putApiMapsMapIdLikeResponse> => {

  const res = await fetch(getPutApiMapsMapIdLikeUrl(mapId),
  {
    ...options,
    method: 'PUT'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiMapsMapIdLikeResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiMapsMapIdLikeResponse
}





export const getPutApiMapsMapIdLikeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiMapsMapIdLike>>, TError,{mapId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiMapsMapIdLike>>, TError,{mapId: string}, TContext> => {

const mutationKey = ['putApiMapsMapIdLike'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiMapsMapIdLike>>, {mapId: string}> = (props) => {
          const {mapId} = props ?? {};

          return  putApiMapsMapIdLike(mapId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiMapsMapIdLikeMutationResult = NonNullable<Awaited<ReturnType<typeof putApiMapsMapIdLike>>>

    export type PutApiMapsMapIdLikeMutationError = void

    export const usePutApiMapsMapIdLike = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiMapsMapIdLike>>, TError,{mapId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiMapsMapIdLike>>,
        TError,
        {mapId: string},
        TContext
      > => {
      return useMutation(getPutApiMapsMapIdLikeMutationOptions(options), queryClient);
    }
    export type deleteApiMapsMapIdLikeResponse204 = {
  data: void
  status: 204
}

export type deleteApiMapsMapIdLikeResponseSuccess = (deleteApiMapsMapIdLikeResponse204) & {
  headers: Headers;
};
;

export type deleteApiMapsMapIdLikeResponse = (deleteApiMapsMapIdLikeResponseSuccess)

export const getDeleteApiMapsMapIdLikeUrl = (mapId: string,) => {




  return `/api/maps/${mapId}/like`
}

export const deleteApiMapsMapIdLike = async (mapId: string, options?: RequestInit): Promise<deleteApiMapsMapIdLikeResponse> => {

  const res = await fetch(getDeleteApiMapsMapIdLikeUrl(mapId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiMapsMapIdLikeResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiMapsMapIdLikeResponse
}





export const getDeleteApiMapsMapIdLikeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapsMapIdLike>>, TError,{mapId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapsMapIdLike>>, TError,{mapId: string}, TContext> => {

const mutationKey = ['deleteApiMapsMapIdLike'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMapsMapIdLike>>, {mapId: string}> = (props) => {
          const {mapId} = props ?? {};

          return  deleteApiMapsMapIdLike(mapId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiMapsMapIdLikeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMapsMapIdLike>>>

    export type DeleteApiMapsMapIdLikeMutationError = unknown

    export const useDeleteApiMapsMapIdLike = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapsMapIdLike>>, TError,{mapId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiMapsMapIdLike>>,
        TError,
        {mapId: string},
        TContext
      > => {
      return useMutation(getDeleteApiMapsMapIdLikeMutationOptions(options), queryClient);
    }
