/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getUserAvatarResponse200 = {
  data: void
  status: 200
}

export type getUserAvatarResponse404 = {
  data: void
  status: 404
}

export type getUserAvatarResponseSuccess = (getUserAvatarResponse200) & {
  headers: Headers;
};
export type getUserAvatarResponseError = (getUserAvatarResponse404) & {
  headers: Headers;
};

export type getUserAvatarResponse = (getUserAvatarResponseSuccess | getUserAvatarResponseError)

export const getGetUserAvatarUrl = (userId: string,) => {




  return `/api/users/${userId}/avatar`
}

/**
 * Serve a user's uploaded avatar image.
 */
export const getUserAvatar = async (userId: string, options?: RequestInit): Promise<getUserAvatarResponse> => {

  const res = await fetch(getGetUserAvatarUrl(userId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserAvatarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getUserAvatarResponse
}





export const getGetUserAvatarQueryKey = (userId: string,) => {
    return [
    `/api/users/${userId}/avatar`
    ] as const;
    }


export const getGetUserAvatarQueryOptions = <TData = Awaited<ReturnType<typeof getUserAvatar>>, TError = void>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAvatar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserAvatarQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserAvatar>>> = ({ signal }) => getUserAvatar(userId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserAvatar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof getUserAvatar>>>
export type GetUserAvatarQueryError = void


export function useGetUserAvatar<TData = Awaited<ReturnType<typeof getUserAvatar>>, TError = void>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAvatar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserAvatar>>,
          TError,
          Awaited<ReturnType<typeof getUserAvatar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserAvatar<TData = Awaited<ReturnType<typeof getUserAvatar>>, TError = void>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAvatar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserAvatar>>,
          TError,
          Awaited<ReturnType<typeof getUserAvatar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserAvatar<TData = Awaited<ReturnType<typeof getUserAvatar>>, TError = void>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAvatar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserAvatar<TData = Awaited<ReturnType<typeof getUserAvatar>>, TError = void>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAvatar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserAvatarQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getUserBannerResponse200 = {
  data: void
  status: 200
}

export type getUserBannerResponse404 = {
  data: void
  status: 404
}

export type getUserBannerResponseSuccess = (getUserBannerResponse200) & {
  headers: Headers;
};
export type getUserBannerResponseError = (getUserBannerResponse404) & {
  headers: Headers;
};

export type getUserBannerResponse = (getUserBannerResponseSuccess | getUserBannerResponseError)

export const getGetUserBannerUrl = (userId: string,) => {




  return `/api/users/${userId}/banner`
}

/**
 * Serve a user's uploaded profile banner image.
 */
export const getUserBanner = async (userId: string, options?: RequestInit): Promise<getUserBannerResponse> => {

  const res = await fetch(getGetUserBannerUrl(userId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserBannerResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getUserBannerResponse
}





export const getGetUserBannerQueryKey = (userId: string,) => {
    return [
    `/api/users/${userId}/banner`
    ] as const;
    }


export const getGetUserBannerQueryOptions = <TData = Awaited<ReturnType<typeof getUserBanner>>, TError = void>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBanner>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserBannerQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBanner>>> = ({ signal }) => getUserBanner(userId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserBanner>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserBannerQueryResult = NonNullable<Awaited<ReturnType<typeof getUserBanner>>>
export type GetUserBannerQueryError = void


export function useGetUserBanner<TData = Awaited<ReturnType<typeof getUserBanner>>, TError = void>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBanner>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBanner>>,
          TError,
          Awaited<ReturnType<typeof getUserBanner>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBanner<TData = Awaited<ReturnType<typeof getUserBanner>>, TError = void>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBanner>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBanner>>,
          TError,
          Awaited<ReturnType<typeof getUserBanner>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBanner<TData = Awaited<ReturnType<typeof getUserBanner>>, TError = void>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBanner>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserBanner<TData = Awaited<ReturnType<typeof getUserBanner>>, TError = void>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBanner>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserBannerQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






