/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PublicProfileDto
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPublicProfileResponse200 = {
  data: PublicProfileDto
  status: 200
}

export type getPublicProfileResponse404 = {
  data: void
  status: 404
}

export type getPublicProfileResponseSuccess = (getPublicProfileResponse200) & {
  headers: Headers;
};
export type getPublicProfileResponseError = (getPublicProfileResponse404) & {
  headers: Headers;
};

export type getPublicProfileResponse = (getPublicProfileResponseSuccess | getPublicProfileResponseError)

export const getGetPublicProfileUrl = (handle: string,) => {




  return `/api/profiles/${handle}`
}

/**
 * Get a user's public profile by handle. Sections are included only when the owner has made them public.
 */
export const getPublicProfile = async (handle: string, options?: RequestInit): Promise<getPublicProfileResponse> => {

  const res = await fetch(getGetPublicProfileUrl(handle),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPublicProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPublicProfileResponse
}





export const getGetPublicProfileQueryKey = (handle: string,) => {
    return [
    `/api/profiles/${handle}`
    ] as const;
    }


export const getGetPublicProfileQueryOptions = <TData = Awaited<ReturnType<typeof getPublicProfile>>, TError = void>(handle: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicProfile>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicProfileQueryKey(handle);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicProfile>>> = ({ signal }) => getPublicProfile(handle, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: handle !== null && handle !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPublicProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicProfile>>>
export type GetPublicProfileQueryError = void


export function useGetPublicProfile<TData = Awaited<ReturnType<typeof getPublicProfile>>, TError = void>(
 handle: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicProfile>>,
          TError,
          Awaited<ReturnType<typeof getPublicProfile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicProfile<TData = Awaited<ReturnType<typeof getPublicProfile>>, TError = void>(
 handle: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicProfile>>,
          TError,
          Awaited<ReturnType<typeof getPublicProfile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicProfile<TData = Awaited<ReturnType<typeof getPublicProfile>>, TError = void>(
 handle: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicProfile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPublicProfile<TData = Awaited<ReturnType<typeof getPublicProfile>>, TError = void>(
 handle: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicProfile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPublicProfileQueryOptions(handle,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






