/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HealthIngestTokenDto,
  HeartRateIngestDto,
  HeartRateIngestResultDto
} from '../model';





export type generateHealthIngestTokenResponse200 = {
  data: HealthIngestTokenDto
  status: 200
}

export type generateHealthIngestTokenResponse401 = {
  data: void
  status: 401
}

export type generateHealthIngestTokenResponseSuccess = (generateHealthIngestTokenResponse200) & {
  headers: Headers;
};
export type generateHealthIngestTokenResponseError = (generateHealthIngestTokenResponse401) & {
  headers: Headers;
};

export type generateHealthIngestTokenResponse = (generateHealthIngestTokenResponseSuccess | generateHealthIngestTokenResponseError)

export const getGenerateHealthIngestTokenUrl = () => {




  return `/api/health/ingest-token`
}

/**
 * Generate or rotate the wearable ingest token (plaintext shown once).
 */
export const generateHealthIngestToken = async ( options?: RequestInit): Promise<generateHealthIngestTokenResponse> => {

  const res = await fetch(getGenerateHealthIngestTokenUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: generateHealthIngestTokenResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generateHealthIngestTokenResponse
}





export const getGenerateHealthIngestTokenMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateHealthIngestToken>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generateHealthIngestToken>>, TError,void, TContext> => {

const mutationKey = ['generateHealthIngestToken'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateHealthIngestToken>>, void> = () => {


          return  generateHealthIngestToken(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GenerateHealthIngestTokenMutationResult = NonNullable<Awaited<ReturnType<typeof generateHealthIngestToken>>>

    export type GenerateHealthIngestTokenMutationError = void

    export const useGenerateHealthIngestToken = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateHealthIngestToken>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateHealthIngestToken>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGenerateHealthIngestTokenMutationOptions(options), queryClient);
    }
    export type ingestHeartRateResponse200 = {
  data: HeartRateIngestResultDto
  status: 200
}

export type ingestHeartRateResponse400 = {
  data: void
  status: 400
}

export type ingestHeartRateResponse401 = {
  data: void
  status: 401
}

export type ingestHeartRateResponseSuccess = (ingestHeartRateResponse200) & {
  headers: Headers;
};
export type ingestHeartRateResponseError = (ingestHeartRateResponse400 | ingestHeartRateResponse401) & {
  headers: Headers;
};

export type ingestHeartRateResponse = (ingestHeartRateResponseSuccess | ingestHeartRateResponseError)

export const getIngestHeartRateUrl = () => {




  return `/api/health/ingest/heartrate`
}

/**
 * Push a batch of heart-rate samples authenticated by the ingest token header.
 */
export const ingestHeartRate = async (heartRateIngestDto: HeartRateIngestDto, options?: RequestInit): Promise<ingestHeartRateResponse> => {

  const res = await fetch(getIngestHeartRateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(heartRateIngestDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ingestHeartRateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as ingestHeartRateResponse
}





export const getIngestHeartRateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestHeartRate>>, TError,{data: HeartRateIngestDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof ingestHeartRate>>, TError,{data: HeartRateIngestDto}, TContext> => {

const mutationKey = ['ingestHeartRate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ingestHeartRate>>, {data: HeartRateIngestDto}> = (props) => {
          const {data} = props ?? {};

          return  ingestHeartRate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type IngestHeartRateMutationResult = NonNullable<Awaited<ReturnType<typeof ingestHeartRate>>>
    export type IngestHeartRateMutationBody = HeartRateIngestDto
    export type IngestHeartRateMutationError = void

    export const useIngestHeartRate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestHeartRate>>, TError,{data: HeartRateIngestDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ingestHeartRate>>,
        TError,
        {data: HeartRateIngestDto},
        TContext
      > => {
      return useMutation(getIngestHeartRateMutationOptions(options), queryClient);
    }
