/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateMapListDto,
  GetApiListsParams,
  MapListDetailDto,
  MapListSummaryDto,
  UpdateMapListDto
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiListsResponse200 = {
  data: MapListSummaryDto[]
  status: 200
}

export type getApiListsResponseSuccess = (getApiListsResponse200) & {
  headers: Headers;
};
;

export type getApiListsResponse = (getApiListsResponseSuccess)

export const getGetApiListsUrl = (params?: GetApiListsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/lists?${stringifiedParams}` : `/api/lists`
}

export const getApiLists = async (params?: GetApiListsParams, options?: RequestInit): Promise<getApiListsResponse> => {

  const res = await fetch(getGetApiListsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiListsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiListsResponse
}





export const getGetApiListsQueryKey = (params?: GetApiListsParams,) => {
    return [
    `/api/lists`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiListsQueryOptions = <TData = Awaited<ReturnType<typeof getApiLists>>, TError = unknown>(params?: GetApiListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLists>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiListsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLists>>> = ({ signal }) => getApiLists(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiListsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLists>>>
export type GetApiListsQueryError = unknown


export function useGetApiLists<TData = Awaited<ReturnType<typeof getApiLists>>, TError = unknown>(
 params: undefined |  GetApiListsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLists>>,
          TError,
          Awaited<ReturnType<typeof getApiLists>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLists<TData = Awaited<ReturnType<typeof getApiLists>>, TError = unknown>(
 params?: GetApiListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLists>>,
          TError,
          Awaited<ReturnType<typeof getApiLists>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLists<TData = Awaited<ReturnType<typeof getApiLists>>, TError = unknown>(
 params?: GetApiListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLists>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiLists<TData = Awaited<ReturnType<typeof getApiLists>>, TError = unknown>(
 params?: GetApiListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLists>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiListsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiListsResponse201 = {
  data: MapListSummaryDto
  status: 201
}

export type postApiListsResponse400 = {
  data: void
  status: 400
}

export type postApiListsResponseSuccess = (postApiListsResponse201) & {
  headers: Headers;
};
export type postApiListsResponseError = (postApiListsResponse400) & {
  headers: Headers;
};

export type postApiListsResponse = (postApiListsResponseSuccess | postApiListsResponseError)

export const getPostApiListsUrl = () => {




  return `/api/lists`
}

export const postApiLists = async (createMapListDto: CreateMapListDto, options?: RequestInit): Promise<postApiListsResponse> => {

  const res = await fetch(getPostApiListsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createMapListDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiListsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiListsResponse
}





export const getPostApiListsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLists>>, TError,{data: CreateMapListDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiLists>>, TError,{data: CreateMapListDto}, TContext> => {

const mutationKey = ['postApiLists'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLists>>, {data: CreateMapListDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiLists(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiListsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLists>>>
    export type PostApiListsMutationBody = CreateMapListDto
    export type PostApiListsMutationError = void

    export const usePostApiLists = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLists>>, TError,{data: CreateMapListDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLists>>,
        TError,
        {data: CreateMapListDto},
        TContext
      > => {
      return useMutation(getPostApiListsMutationOptions(options), queryClient);
    }
    export type getApiListsListIdResponse200 = {
  data: MapListDetailDto
  status: 200
}

export type getApiListsListIdResponse404 = {
  data: void
  status: 404
}

export type getApiListsListIdResponseSuccess = (getApiListsListIdResponse200) & {
  headers: Headers;
};
export type getApiListsListIdResponseError = (getApiListsListIdResponse404) & {
  headers: Headers;
};

export type getApiListsListIdResponse = (getApiListsListIdResponseSuccess | getApiListsListIdResponseError)

export const getGetApiListsListIdUrl = (listId: string,) => {




  return `/api/lists/${listId}`
}

export const getApiListsListId = async (listId: string, options?: RequestInit): Promise<getApiListsListIdResponse> => {

  const res = await fetch(getGetApiListsListIdUrl(listId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiListsListIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiListsListIdResponse
}





export const getGetApiListsListIdQueryKey = (listId: string,) => {
    return [
    `/api/lists/${listId}`
    ] as const;
    }


export const getGetApiListsListIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiListsListId>>, TError = void>(listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListsListId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiListsListIdQueryKey(listId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiListsListId>>> = ({ signal }) => getApiListsListId(listId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: listId !== null && listId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiListsListId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiListsListIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiListsListId>>>
export type GetApiListsListIdQueryError = void


export function useGetApiListsListId<TData = Awaited<ReturnType<typeof getApiListsListId>>, TError = void>(
 listId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListsListId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiListsListId>>,
          TError,
          Awaited<ReturnType<typeof getApiListsListId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiListsListId<TData = Awaited<ReturnType<typeof getApiListsListId>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListsListId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiListsListId>>,
          TError,
          Awaited<ReturnType<typeof getApiListsListId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiListsListId<TData = Awaited<ReturnType<typeof getApiListsListId>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListsListId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiListsListId<TData = Awaited<ReturnType<typeof getApiListsListId>>, TError = void>(
 listId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListsListId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiListsListIdQueryOptions(listId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type patchApiListsListIdResponse204 = {
  data: void
  status: 204
}

export type patchApiListsListIdResponse400 = {
  data: void
  status: 400
}

export type patchApiListsListIdResponse404 = {
  data: void
  status: 404
}

export type patchApiListsListIdResponseSuccess = (patchApiListsListIdResponse204) & {
  headers: Headers;
};
export type patchApiListsListIdResponseError = (patchApiListsListIdResponse400 | patchApiListsListIdResponse404) & {
  headers: Headers;
};

export type patchApiListsListIdResponse = (patchApiListsListIdResponseSuccess | patchApiListsListIdResponseError)

export const getPatchApiListsListIdUrl = (listId: string,) => {




  return `/api/lists/${listId}`
}

export const patchApiListsListId = async (listId: string,
    updateMapListDto: UpdateMapListDto, options?: RequestInit): Promise<patchApiListsListIdResponse> => {

  const res = await fetch(getPatchApiListsListIdUrl(listId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateMapListDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchApiListsListIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as patchApiListsListIdResponse
}





export const getPatchApiListsListIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiListsListId>>, TError,{listId: string;data: UpdateMapListDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiListsListId>>, TError,{listId: string;data: UpdateMapListDto}, TContext> => {

const mutationKey = ['patchApiListsListId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiListsListId>>, {listId: string;data: UpdateMapListDto}> = (props) => {
          const {listId,data} = props ?? {};

          return  patchApiListsListId(listId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiListsListIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiListsListId>>>
    export type PatchApiListsListIdMutationBody = UpdateMapListDto
    export type PatchApiListsListIdMutationError = void

    export const usePatchApiListsListId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiListsListId>>, TError,{listId: string;data: UpdateMapListDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiListsListId>>,
        TError,
        {listId: string;data: UpdateMapListDto},
        TContext
      > => {
      return useMutation(getPatchApiListsListIdMutationOptions(options), queryClient);
    }
    export type deleteApiListsListIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiListsListIdResponse404 = {
  data: void
  status: 404
}

export type deleteApiListsListIdResponseSuccess = (deleteApiListsListIdResponse204) & {
  headers: Headers;
};
export type deleteApiListsListIdResponseError = (deleteApiListsListIdResponse404) & {
  headers: Headers;
};

export type deleteApiListsListIdResponse = (deleteApiListsListIdResponseSuccess | deleteApiListsListIdResponseError)

export const getDeleteApiListsListIdUrl = (listId: string,) => {




  return `/api/lists/${listId}`
}

export const deleteApiListsListId = async (listId: string, options?: RequestInit): Promise<deleteApiListsListIdResponse> => {

  const res = await fetch(getDeleteApiListsListIdUrl(listId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiListsListIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiListsListIdResponse
}





export const getDeleteApiListsListIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiListsListId>>, TError,{listId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiListsListId>>, TError,{listId: string}, TContext> => {

const mutationKey = ['deleteApiListsListId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiListsListId>>, {listId: string}> = (props) => {
          const {listId} = props ?? {};

          return  deleteApiListsListId(listId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiListsListIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiListsListId>>>

    export type DeleteApiListsListIdMutationError = void

    export const useDeleteApiListsListId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiListsListId>>, TError,{listId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiListsListId>>,
        TError,
        {listId: string},
        TContext
      > => {
      return useMutation(getDeleteApiListsListIdMutationOptions(options), queryClient);
    }
    export type putApiListsListIdMapsMapIdResponse204 = {
  data: void
  status: 204
}

export type putApiListsListIdMapsMapIdResponse404 = {
  data: void
  status: 404
}

export type putApiListsListIdMapsMapIdResponseSuccess = (putApiListsListIdMapsMapIdResponse204) & {
  headers: Headers;
};
export type putApiListsListIdMapsMapIdResponseError = (putApiListsListIdMapsMapIdResponse404) & {
  headers: Headers;
};

export type putApiListsListIdMapsMapIdResponse = (putApiListsListIdMapsMapIdResponseSuccess | putApiListsListIdMapsMapIdResponseError)

export const getPutApiListsListIdMapsMapIdUrl = (listId: string,
    mapId: string,) => {




  return `/api/lists/${listId}/maps/${mapId}`
}

export const putApiListsListIdMapsMapId = async (listId: string,
    mapId: string, options?: RequestInit): Promise<putApiListsListIdMapsMapIdResponse> => {

  const res = await fetch(getPutApiListsListIdMapsMapIdUrl(listId,mapId),
  {
    ...options,
    method: 'PUT'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiListsListIdMapsMapIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiListsListIdMapsMapIdResponse
}





export const getPutApiListsListIdMapsMapIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiListsListIdMapsMapId>>, TError,{listId: string;mapId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiListsListIdMapsMapId>>, TError,{listId: string;mapId: string}, TContext> => {

const mutationKey = ['putApiListsListIdMapsMapId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiListsListIdMapsMapId>>, {listId: string;mapId: string}> = (props) => {
          const {listId,mapId} = props ?? {};

          return  putApiListsListIdMapsMapId(listId,mapId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiListsListIdMapsMapIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiListsListIdMapsMapId>>>

    export type PutApiListsListIdMapsMapIdMutationError = void

    export const usePutApiListsListIdMapsMapId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiListsListIdMapsMapId>>, TError,{listId: string;mapId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiListsListIdMapsMapId>>,
        TError,
        {listId: string;mapId: string},
        TContext
      > => {
      return useMutation(getPutApiListsListIdMapsMapIdMutationOptions(options), queryClient);
    }
    export type deleteApiListsListIdMapsMapIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiListsListIdMapsMapIdResponse404 = {
  data: void
  status: 404
}

export type deleteApiListsListIdMapsMapIdResponseSuccess = (deleteApiListsListIdMapsMapIdResponse204) & {
  headers: Headers;
};
export type deleteApiListsListIdMapsMapIdResponseError = (deleteApiListsListIdMapsMapIdResponse404) & {
  headers: Headers;
};

export type deleteApiListsListIdMapsMapIdResponse = (deleteApiListsListIdMapsMapIdResponseSuccess | deleteApiListsListIdMapsMapIdResponseError)

export const getDeleteApiListsListIdMapsMapIdUrl = (listId: string,
    mapId: string,) => {




  return `/api/lists/${listId}/maps/${mapId}`
}

export const deleteApiListsListIdMapsMapId = async (listId: string,
    mapId: string, options?: RequestInit): Promise<deleteApiListsListIdMapsMapIdResponse> => {

  const res = await fetch(getDeleteApiListsListIdMapsMapIdUrl(listId,mapId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiListsListIdMapsMapIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiListsListIdMapsMapIdResponse
}





export const getDeleteApiListsListIdMapsMapIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiListsListIdMapsMapId>>, TError,{listId: string;mapId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiListsListIdMapsMapId>>, TError,{listId: string;mapId: string}, TContext> => {

const mutationKey = ['deleteApiListsListIdMapsMapId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiListsListIdMapsMapId>>, {listId: string;mapId: string}> = (props) => {
          const {listId,mapId} = props ?? {};

          return  deleteApiListsListIdMapsMapId(listId,mapId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiListsListIdMapsMapIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiListsListIdMapsMapId>>>

    export type DeleteApiListsListIdMapsMapIdMutationError = void

    export const useDeleteApiListsListIdMapsMapId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiListsListIdMapsMapId>>, TError,{listId: string;mapId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiListsListIdMapsMapId>>,
        TError,
        {listId: string;mapId: string},
        TContext
      > => {
      return useMutation(getDeleteApiListsListIdMapsMapIdMutationOptions(options), queryClient);
    }
