/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiSessionsParams,
  GetApiSessionsPbParams,
  NoteItemDto,
  PagedResultOfPlaySessionListItemDto,
  PersonalBestDto,
  PlaySessionDetailDto,
  PlaySessionMotionDto,
  PlaySessionTimelineDto,
  SessionTopDifficultyDto,
  SkillProfileDto,
  TrendBucketDto,
  UserStatsDto
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiSessionsResponse200 = {
  data: PagedResultOfPlaySessionListItemDto
  status: 200
}

export type getApiSessionsResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsResponseSuccess = (getApiSessionsResponse200) & {
  headers: Headers;
};
export type getApiSessionsResponseError = (getApiSessionsResponse401) & {
  headers: Headers;
};

export type getApiSessionsResponse = (getApiSessionsResponseSuccess | getApiSessionsResponseError)

export const getGetApiSessionsUrl = (params?: GetApiSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sessions?${stringifiedParams}` : `/api/sessions`
}

export const getApiSessions = async (params?: GetApiSessionsParams, options?: RequestInit): Promise<getApiSessionsResponse> => {

  const res = await fetch(getGetApiSessionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsResponse
}





export const getGetApiSessionsQueryKey = (params?: GetApiSessionsParams,) => {
    return [
    `/api/sessions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessions>>, TError = void>(params?: GetApiSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessions>>> = ({ signal }) => getApiSessions(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessions>>>
export type GetApiSessionsQueryError = void


export function useGetApiSessions<TData = Awaited<ReturnType<typeof getApiSessions>>, TError = void>(
 params: undefined |  GetApiSessionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessions>>,
          TError,
          Awaited<ReturnType<typeof getApiSessions>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessions<TData = Awaited<ReturnType<typeof getApiSessions>>, TError = void>(
 params?: GetApiSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessions>>,
          TError,
          Awaited<ReturnType<typeof getApiSessions>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessions<TData = Awaited<ReturnType<typeof getApiSessions>>, TError = void>(
 params?: GetApiSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessions<TData = Awaited<ReturnType<typeof getApiSessions>>, TError = void>(
 params?: GetApiSessionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsIdResponse200 = {
  data: PlaySessionDetailDto
  status: 200
}

export type getApiSessionsIdResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsIdResponse404 = {
  data: void
  status: 404
}

export type getApiSessionsIdResponseSuccess = (getApiSessionsIdResponse200) & {
  headers: Headers;
};
export type getApiSessionsIdResponseError = (getApiSessionsIdResponse401 | getApiSessionsIdResponse404) & {
  headers: Headers;
};

export type getApiSessionsIdResponse = (getApiSessionsIdResponseSuccess | getApiSessionsIdResponseError)

export const getGetApiSessionsIdUrl = (id: string,) => {




  return `/api/sessions/${id}`
}

export const getApiSessionsId = async (id: string, options?: RequestInit): Promise<getApiSessionsIdResponse> => {

  const res = await fetch(getGetApiSessionsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsIdResponse
}





export const getGetApiSessionsIdQueryKey = (id: string,) => {
    return [
    `/api/sessions/${id}`
    ] as const;
    }


export const getGetApiSessionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsId>>> = ({ signal }) => getApiSessionsId(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsId>>>
export type GetApiSessionsIdQueryError = void


export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsId>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsId<TData = Awaited<ReturnType<typeof getApiSessionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsIdTimelineResponse200 = {
  data: PlaySessionTimelineDto
  status: 200
}

export type getApiSessionsIdTimelineResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsIdTimelineResponse404 = {
  data: void
  status: 404
}

export type getApiSessionsIdTimelineResponseSuccess = (getApiSessionsIdTimelineResponse200) & {
  headers: Headers;
};
export type getApiSessionsIdTimelineResponseError = (getApiSessionsIdTimelineResponse401 | getApiSessionsIdTimelineResponse404) & {
  headers: Headers;
};

export type getApiSessionsIdTimelineResponse = (getApiSessionsIdTimelineResponseSuccess | getApiSessionsIdTimelineResponseError)

export const getGetApiSessionsIdTimelineUrl = (id: string,) => {




  return `/api/sessions/${id}/timeline`
}

export const getApiSessionsIdTimeline = async (id: string, options?: RequestInit): Promise<getApiSessionsIdTimelineResponse> => {

  const res = await fetch(getGetApiSessionsIdTimelineUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsIdTimelineResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsIdTimelineResponse
}





export const getGetApiSessionsIdTimelineQueryKey = (id: string,) => {
    return [
    `/api/sessions/${id}/timeline`
    ] as const;
    }


export const getGetApiSessionsIdTimelineQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsIdTimelineQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsIdTimeline>>> = ({ signal }) => getApiSessionsIdTimeline(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsIdTimelineQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsIdTimeline>>>
export type GetApiSessionsIdTimelineQueryError = void


export function useGetApiSessionsIdTimeline<TData = Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdTimeline>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdTimeline>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdTimeline<TData = Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdTimeline>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdTimeline>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdTimeline<TData = Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsIdTimeline<TData = Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTimeline>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsIdTimelineQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsIdNotesResponse200 = {
  data: NoteItemDto[]
  status: 200
}

export type getApiSessionsIdNotesResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsIdNotesResponse404 = {
  data: void
  status: 404
}

export type getApiSessionsIdNotesResponseSuccess = (getApiSessionsIdNotesResponse200) & {
  headers: Headers;
};
export type getApiSessionsIdNotesResponseError = (getApiSessionsIdNotesResponse401 | getApiSessionsIdNotesResponse404) & {
  headers: Headers;
};

export type getApiSessionsIdNotesResponse = (getApiSessionsIdNotesResponseSuccess | getApiSessionsIdNotesResponseError)

export const getGetApiSessionsIdNotesUrl = (id: string,) => {




  return `/api/sessions/${id}/notes`
}

export const getApiSessionsIdNotes = async (id: string, options?: RequestInit): Promise<getApiSessionsIdNotesResponse> => {

  const res = await fetch(getGetApiSessionsIdNotesUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsIdNotesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsIdNotesResponse
}





export const getGetApiSessionsIdNotesQueryKey = (id: string,) => {
    return [
    `/api/sessions/${id}/notes`
    ] as const;
    }


export const getGetApiSessionsIdNotesQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsIdNotesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsIdNotes>>> = ({ signal }) => getApiSessionsIdNotes(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsIdNotesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsIdNotes>>>
export type GetApiSessionsIdNotesQueryError = void


export function useGetApiSessionsIdNotes<TData = Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdNotes>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdNotes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdNotes<TData = Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdNotes>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdNotes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdNotes<TData = Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsIdNotes<TData = Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdNotes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsIdNotesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsIdMotionResponse200 = {
  data: PlaySessionMotionDto
  status: 200
}

export type getApiSessionsIdMotionResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsIdMotionResponse404 = {
  data: void
  status: 404
}

export type getApiSessionsIdMotionResponseSuccess = (getApiSessionsIdMotionResponse200) & {
  headers: Headers;
};
export type getApiSessionsIdMotionResponseError = (getApiSessionsIdMotionResponse401 | getApiSessionsIdMotionResponse404) & {
  headers: Headers;
};

export type getApiSessionsIdMotionResponse = (getApiSessionsIdMotionResponseSuccess | getApiSessionsIdMotionResponseError)

export const getGetApiSessionsIdMotionUrl = (id: string,) => {




  return `/api/sessions/${id}/motion`
}

export const getApiSessionsIdMotion = async (id: string, options?: RequestInit): Promise<getApiSessionsIdMotionResponse> => {

  const res = await fetch(getGetApiSessionsIdMotionUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsIdMotionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsIdMotionResponse
}





export const getGetApiSessionsIdMotionQueryKey = (id: string,) => {
    return [
    `/api/sessions/${id}/motion`
    ] as const;
    }


export const getGetApiSessionsIdMotionQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsIdMotionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsIdMotion>>> = ({ signal }) => getApiSessionsIdMotion(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsIdMotionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsIdMotion>>>
export type GetApiSessionsIdMotionQueryError = void


export function useGetApiSessionsIdMotion<TData = Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdMotion>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdMotion>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdMotion<TData = Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdMotion>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdMotion>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdMotion<TData = Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsIdMotion<TData = Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdMotion>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsIdMotionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsStatsResponse200 = {
  data: UserStatsDto
  status: 200
}

export type getApiSessionsStatsResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsStatsResponseSuccess = (getApiSessionsStatsResponse200) & {
  headers: Headers;
};
export type getApiSessionsStatsResponseError = (getApiSessionsStatsResponse401) & {
  headers: Headers;
};

export type getApiSessionsStatsResponse = (getApiSessionsStatsResponseSuccess | getApiSessionsStatsResponseError)

export const getGetApiSessionsStatsUrl = () => {




  return `/api/sessions/stats`
}

export const getApiSessionsStats = async ( options?: RequestInit): Promise<getApiSessionsStatsResponse> => {

  const res = await fetch(getGetApiSessionsStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsStatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsStatsResponse
}





export const getGetApiSessionsStatsQueryKey = () => {
    return [
    `/api/sessions/stats`
    ] as const;
    }


export const getGetApiSessionsStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsStats>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsStats>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsStats>>> = ({ signal }) => getApiSessionsStats({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsStats>>>
export type GetApiSessionsStatsQueryError = void


export function useGetApiSessionsStats<TData = Awaited<ReturnType<typeof getApiSessionsStats>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsStats>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsStats<TData = Awaited<ReturnType<typeof getApiSessionsStats>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsStats>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsStats<TData = Awaited<ReturnType<typeof getApiSessionsStats>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsStats>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsStats<TData = Awaited<ReturnType<typeof getApiSessionsStats>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsStats>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsSkillResponse200 = {
  data: SkillProfileDto
  status: 200
}

export type getApiSessionsSkillResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsSkillResponseSuccess = (getApiSessionsSkillResponse200) & {
  headers: Headers;
};
export type getApiSessionsSkillResponseError = (getApiSessionsSkillResponse401) & {
  headers: Headers;
};

export type getApiSessionsSkillResponse = (getApiSessionsSkillResponseSuccess | getApiSessionsSkillResponseError)

export const getGetApiSessionsSkillUrl = () => {




  return `/api/sessions/skill`
}

export const getApiSessionsSkill = async ( options?: RequestInit): Promise<getApiSessionsSkillResponse> => {

  const res = await fetch(getGetApiSessionsSkillUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsSkillResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsSkillResponse
}





export const getGetApiSessionsSkillQueryKey = () => {
    return [
    `/api/sessions/skill`
    ] as const;
    }


export const getGetApiSessionsSkillQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsSkill>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsSkill>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsSkillQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsSkill>>> = ({ signal }) => getApiSessionsSkill({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsSkill>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsSkillQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsSkill>>>
export type GetApiSessionsSkillQueryError = void


export function useGetApiSessionsSkill<TData = Awaited<ReturnType<typeof getApiSessionsSkill>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsSkill>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsSkill>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsSkill>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsSkill<TData = Awaited<ReturnType<typeof getApiSessionsSkill>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsSkill>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsSkill>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsSkill>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsSkill<TData = Awaited<ReturnType<typeof getApiSessionsSkill>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsSkill>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsSkill<TData = Awaited<ReturnType<typeof getApiSessionsSkill>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsSkill>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsSkillQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsTrendsResponse200 = {
  data: TrendBucketDto[]
  status: 200
}

export type getApiSessionsTrendsResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsTrendsResponseSuccess = (getApiSessionsTrendsResponse200) & {
  headers: Headers;
};
export type getApiSessionsTrendsResponseError = (getApiSessionsTrendsResponse401) & {
  headers: Headers;
};

export type getApiSessionsTrendsResponse = (getApiSessionsTrendsResponseSuccess | getApiSessionsTrendsResponseError)

export const getGetApiSessionsTrendsUrl = () => {




  return `/api/sessions/trends`
}

export const getApiSessionsTrends = async ( options?: RequestInit): Promise<getApiSessionsTrendsResponse> => {

  const res = await fetch(getGetApiSessionsTrendsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsTrendsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsTrendsResponse
}





export const getGetApiSessionsTrendsQueryKey = () => {
    return [
    `/api/sessions/trends`
    ] as const;
    }


export const getGetApiSessionsTrendsQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsTrends>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsTrends>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsTrendsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsTrends>>> = ({ signal }) => getApiSessionsTrends({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsTrends>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsTrendsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsTrends>>>
export type GetApiSessionsTrendsQueryError = void


export function useGetApiSessionsTrends<TData = Awaited<ReturnType<typeof getApiSessionsTrends>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsTrends>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsTrends>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsTrends>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsTrends<TData = Awaited<ReturnType<typeof getApiSessionsTrends>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsTrends>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsTrends>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsTrends>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsTrends<TData = Awaited<ReturnType<typeof getApiSessionsTrends>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsTrends>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsTrends<TData = Awaited<ReturnType<typeof getApiSessionsTrends>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsTrends>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsTrendsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsPbResponse200 = {
  data: PersonalBestDto
  status: 200
}

export type getApiSessionsPbResponse400 = {
  data: void
  status: 400
}

export type getApiSessionsPbResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsPbResponseSuccess = (getApiSessionsPbResponse200) & {
  headers: Headers;
};
export type getApiSessionsPbResponseError = (getApiSessionsPbResponse400 | getApiSessionsPbResponse401) & {
  headers: Headers;
};

export type getApiSessionsPbResponse = (getApiSessionsPbResponseSuccess | getApiSessionsPbResponseError)

export const getGetApiSessionsPbUrl = (params: GetApiSessionsPbParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sessions/pb?${stringifiedParams}` : `/api/sessions/pb`
}

export const getApiSessionsPb = async (params: GetApiSessionsPbParams, options?: RequestInit): Promise<getApiSessionsPbResponse> => {

  const res = await fetch(getGetApiSessionsPbUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsPbResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsPbResponse
}





export const getGetApiSessionsPbQueryKey = (params?: GetApiSessionsPbParams,) => {
    return [
    `/api/sessions/pb`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiSessionsPbQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsPb>>, TError = void>(params: GetApiSessionsPbParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsPb>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsPbQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsPb>>> = ({ signal }) => getApiSessionsPb(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsPb>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsPbQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsPb>>>
export type GetApiSessionsPbQueryError = void


export function useGetApiSessionsPb<TData = Awaited<ReturnType<typeof getApiSessionsPb>>, TError = void>(
 params: GetApiSessionsPbParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsPb>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsPb>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsPb>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsPb<TData = Awaited<ReturnType<typeof getApiSessionsPb>>, TError = void>(
 params: GetApiSessionsPbParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsPb>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsPb>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsPb>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsPb<TData = Awaited<ReturnType<typeof getApiSessionsPb>>, TError = void>(
 params: GetApiSessionsPbParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsPb>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsPb<TData = Awaited<ReturnType<typeof getApiSessionsPb>>, TError = void>(
 params: GetApiSessionsPbParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsPb>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsPbQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getApiSessionsIdTopResponse200 = {
  data: SessionTopDifficultyDto[]
  status: 200
}

export type getApiSessionsIdTopResponse401 = {
  data: void
  status: 401
}

export type getApiSessionsIdTopResponse404 = {
  data: void
  status: 404
}

export type getApiSessionsIdTopResponseSuccess = (getApiSessionsIdTopResponse200) & {
  headers: Headers;
};
export type getApiSessionsIdTopResponseError = (getApiSessionsIdTopResponse401 | getApiSessionsIdTopResponse404) & {
  headers: Headers;
};

export type getApiSessionsIdTopResponse = (getApiSessionsIdTopResponseSuccess | getApiSessionsIdTopResponseError)

export const getGetApiSessionsIdTopUrl = (id: string,) => {




  return `/api/sessions/${id}/top`
}

export const getApiSessionsIdTop = async (id: string, options?: RequestInit): Promise<getApiSessionsIdTopResponse> => {

  const res = await fetch(getGetApiSessionsIdTopUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSessionsIdTopResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiSessionsIdTopResponse
}





export const getGetApiSessionsIdTopQueryKey = (id: string,) => {
    return [
    `/api/sessions/${id}/top`
    ] as const;
    }


export const getGetApiSessionsIdTopQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionsIdTopQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionsIdTop>>> = ({ signal }) => getApiSessionsIdTop(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionsIdTopQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionsIdTop>>>
export type GetApiSessionsIdTopQueryError = void


export function useGetApiSessionsIdTop<TData = Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdTop>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdTop>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdTop<TData = Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionsIdTop>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionsIdTop>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionsIdTop<TData = Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionsIdTop<TData = Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionsIdTop>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionsIdTopQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






