/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as MapsIndexRouteImport } from './routes/maps/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as SessionsIdRouteImport } from './routes/sessions/$id'
import { Route as MapsIdRouteImport } from './routes/maps/$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminScoringRouteImport } from './routes/admin/scoring'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIdRoute = MapsIdRouteImport.update({
  id: '/maps/$id',
  path: '/maps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminScoringRoute = AdminScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRouteWithChildren
  '/devices': typeof DevicesRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/admin/scoring': typeof AdminScoringRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/maps/$id': typeof MapsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRouteWithChildren
  '/devices': typeof DevicesRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/admin/scoring': typeof AdminScoringRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/maps/$id': typeof MapsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/u/$handle': typeof UHandleRoute
  '/admin': typeof AdminIndexRoute
  '/maps': typeof MapsIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRouteWithChildren
  '/devices': typeof DevicesRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/admin/scoring': typeof AdminScoringRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/maps/$id': typeof MapsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analysis'
    | '/auth'
    | '/devices'
    | '/live'
    | '/settings'
    | '/admin/scoring'
    | '/auth/login'
    | '/auth/register'
    | '/maps/$id'
    | '/sessions/$id'
    | '/u/$handle'
    | '/admin/'
    | '/maps/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/auth'
    | '/devices'
    | '/live'
    | '/settings'
    | '/admin/scoring'
    | '/auth/login'
    | '/auth/register'
    | '/maps/$id'
    | '/sessions/$id'
    | '/u/$handle'
    | '/admin'
    | '/maps'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analysis'
    | '/auth'
    | '/devices'
    | '/live'
    | '/settings'
    | '/admin/scoring'
    | '/auth/login'
    | '/auth/register'
    | '/maps/$id'
    | '/sessions/$id'
    | '/u/$handle'
    | '/admin/'
    | '/maps/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  AuthRoute: typeof AuthRouteWithChildren
  DevicesRoute: typeof DevicesRoute
  LiveRoute: typeof LiveRoute
  SettingsRoute: typeof SettingsRoute
  MapsIdRoute: typeof MapsIdRoute
  SessionsIdRoute: typeof SessionsIdRoute
  UHandleRoute: typeof UHandleRoute
  MapsIndexRoute: typeof MapsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$id': {
      id: '/maps/$id'
      path: '/maps/$id'
      fullPath: '/maps/$id'
      preLoaderRoute: typeof MapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/scoring': {
      id: '/admin/scoring'
      path: '/scoring'
      fullPath: '/admin/scoring'
      preLoaderRoute: typeof AdminScoringRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminScoringRoute: typeof AdminScoringRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminScoringRoute: AdminScoringRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  AuthRoute: AuthRouteWithChildren,
  DevicesRoute: DevicesRoute,
  LiveRoute: LiveRoute,
  SettingsRoute: SettingsRoute,
  MapsIdRoute: MapsIdRoute,
  SessionsIdRoute: SessionsIdRoute,
  UHandleRoute: UHandleRoute,
  MapsIndexRoute: MapsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
