<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BlurHashSharp"/>
        <PackageReference Include="DotNetEnv"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.IdentityModel.Tokens"/>
        <PackageReference Include="Microsoft.OpenApi"/>
        <PackageReference Include="Minio"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
        <PackageReference Include="Quartz"/>
        <PackageReference Include="Quartz.Extensions.Hosting"/>
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="SkiaSharp"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BeatDash.Beatmaps\Shiron.BeatDash.Beatmaps.csproj"/>
        <ProjectReference Include="..\BeatDash.Data\Shiron.BeatDash.Data.csproj"/>
        <ProjectReference Include="..\BeatDash.DB\Shiron.BeatDash.DB.csproj"/>
    </ItemGroup>

</Project>
