/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticateDeviceDto,
  DeviceResponseDto,
  RegisterDeviceResponseDto,
  TokenPairExpiryDto,
  UpdateDeviceDto
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getDeviceRegisterResponse200 = {
  data: RegisterDeviceResponseDto
  status: 200
}

export type getDeviceRegisterResponseSuccess = (getDeviceRegisterResponse200) & {
  headers: Headers;
};
;

export type getDeviceRegisterResponse = (getDeviceRegisterResponseSuccess)

export const getGetDeviceRegisterUrl = () => {




  return `/device/register`
}

export const getDeviceRegister = async ( options?: RequestInit): Promise<getDeviceRegisterResponse> => {

  const res = await fetch(getGetDeviceRegisterUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDeviceRegisterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDeviceRegisterResponse
}





export const getGetDeviceRegisterQueryKey = () => {
    return [
    `/device/register`
    ] as const;
    }


export const getGetDeviceRegisterQueryOptions = <TData = Awaited<ReturnType<typeof getDeviceRegister>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceRegister>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeviceRegisterQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeviceRegister>>> = ({ signal }) => getDeviceRegister({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeviceRegister>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDeviceRegisterQueryResult = NonNullable<Awaited<ReturnType<typeof getDeviceRegister>>>
export type GetDeviceRegisterQueryError = unknown


export function useGetDeviceRegister<TData = Awaited<ReturnType<typeof getDeviceRegister>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceRegister>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceRegister>>,
          TError,
          Awaited<ReturnType<typeof getDeviceRegister>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeviceRegister<TData = Awaited<ReturnType<typeof getDeviceRegister>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceRegister>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceRegister>>,
          TError,
          Awaited<ReturnType<typeof getDeviceRegister>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeviceRegister<TData = Awaited<ReturnType<typeof getDeviceRegister>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceRegister>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDeviceRegister<TData = Awaited<ReturnType<typeof getDeviceRegister>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceRegister>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDeviceRegisterQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postDeviceAuthenticateResponse200 = {
  data: TokenPairExpiryDto
  status: 200
}

export type postDeviceAuthenticateResponseSuccess = (postDeviceAuthenticateResponse200) & {
  headers: Headers;
};
;

export type postDeviceAuthenticateResponse = (postDeviceAuthenticateResponseSuccess)

export const getPostDeviceAuthenticateUrl = () => {




  return `/device/authenticate`
}

export const postDeviceAuthenticate = async (authenticateDeviceDto: AuthenticateDeviceDto, options?: RequestInit): Promise<postDeviceAuthenticateResponse> => {

  const res = await fetch(getPostDeviceAuthenticateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authenticateDeviceDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postDeviceAuthenticateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postDeviceAuthenticateResponse
}





export const getPostDeviceAuthenticateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDeviceAuthenticate>>, TError,{data: AuthenticateDeviceDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postDeviceAuthenticate>>, TError,{data: AuthenticateDeviceDto}, TContext> => {

const mutationKey = ['postDeviceAuthenticate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDeviceAuthenticate>>, {data: AuthenticateDeviceDto}> = (props) => {
          const {data} = props ?? {};

          return  postDeviceAuthenticate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostDeviceAuthenticateMutationResult = NonNullable<Awaited<ReturnType<typeof postDeviceAuthenticate>>>
    export type PostDeviceAuthenticateMutationBody = AuthenticateDeviceDto
    export type PostDeviceAuthenticateMutationError = unknown

    export const usePostDeviceAuthenticate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDeviceAuthenticate>>, TError,{data: AuthenticateDeviceDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDeviceAuthenticate>>,
        TError,
        {data: AuthenticateDeviceDto},
        TContext
      > => {
      return useMutation(getPostDeviceAuthenticateMutationOptions(options), queryClient);
    }
    export type getDeviceResponse200 = {
  data: DeviceResponseDto[]
  status: 200
}

export type getDeviceResponseSuccess = (getDeviceResponse200) & {
  headers: Headers;
};
;

export type getDeviceResponse = (getDeviceResponseSuccess)

export const getGetDeviceUrl = () => {




  return `/device`
}

export const getDevice = async ( options?: RequestInit): Promise<getDeviceResponse> => {

  const res = await fetch(getGetDeviceUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDeviceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDeviceResponse
}





export const getGetDeviceQueryKey = () => {
    return [
    `/device`
    ] as const;
    }


export const getGetDeviceQueryOptions = <TData = Awaited<ReturnType<typeof getDevice>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeviceQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDevice>>> = ({ signal }) => getDevice({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDeviceQueryResult = NonNullable<Awaited<ReturnType<typeof getDevice>>>
export type GetDeviceQueryError = unknown


export function useGetDevice<TData = Awaited<ReturnType<typeof getDevice>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevice>>,
          TError,
          Awaited<ReturnType<typeof getDevice>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDevice<TData = Awaited<ReturnType<typeof getDevice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevice>>,
          TError,
          Awaited<ReturnType<typeof getDevice>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDevice<TData = Awaited<ReturnType<typeof getDevice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDevice<TData = Awaited<ReturnType<typeof getDevice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDeviceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteDeviceClientIdResponse204 = {
  data: void
  status: 204
}

export type deleteDeviceClientIdResponseSuccess = (deleteDeviceClientIdResponse204) & {
  headers: Headers;
};
;

export type deleteDeviceClientIdResponse = (deleteDeviceClientIdResponseSuccess)

export const getDeleteDeviceClientIdUrl = (clientId: string,) => {




  return `/device/${clientId}`
}

export const deleteDeviceClientId = async (clientId: string, options?: RequestInit): Promise<deleteDeviceClientIdResponse> => {

  const res = await fetch(getDeleteDeviceClientIdUrl(clientId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteDeviceClientIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteDeviceClientIdResponse
}





export const getDeleteDeviceClientIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDeviceClientId>>, TError,{clientId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDeviceClientId>>, TError,{clientId: string}, TContext> => {

const mutationKey = ['deleteDeviceClientId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDeviceClientId>>, {clientId: string}> = (props) => {
          const {clientId} = props ?? {};

          return  deleteDeviceClientId(clientId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDeviceClientIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDeviceClientId>>>

    export type DeleteDeviceClientIdMutationError = unknown

    export const useDeleteDeviceClientId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDeviceClientId>>, TError,{clientId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDeviceClientId>>,
        TError,
        {clientId: string},
        TContext
      > => {
      return useMutation(getDeleteDeviceClientIdMutationOptions(options), queryClient);
    }
    export type patchDeviceClientIdResponse204 = {
  data: void
  status: 204
}

export type patchDeviceClientIdResponseSuccess = (patchDeviceClientIdResponse204) & {
  headers: Headers;
};
;

export type patchDeviceClientIdResponse = (patchDeviceClientIdResponseSuccess)

export const getPatchDeviceClientIdUrl = (clientId: string,) => {




  return `/device/${clientId}`
}

export const patchDeviceClientId = async (clientId: string,
    updateDeviceDto: UpdateDeviceDto, options?: RequestInit): Promise<patchDeviceClientIdResponse> => {

  const res = await fetch(getPatchDeviceClientIdUrl(clientId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateDeviceDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchDeviceClientIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as patchDeviceClientIdResponse
}





export const getPatchDeviceClientIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchDeviceClientId>>, TError,{clientId: string;data: UpdateDeviceDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchDeviceClientId>>, TError,{clientId: string;data: UpdateDeviceDto}, TContext> => {

const mutationKey = ['patchDeviceClientId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchDeviceClientId>>, {clientId: string;data: UpdateDeviceDto}> = (props) => {
          const {clientId,data} = props ?? {};

          return  patchDeviceClientId(clientId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchDeviceClientIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchDeviceClientId>>>
    export type PatchDeviceClientIdMutationBody = UpdateDeviceDto
    export type PatchDeviceClientIdMutationError = unknown

    export const usePatchDeviceClientId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchDeviceClientId>>, TError,{clientId: string;data: UpdateDeviceDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchDeviceClientId>>,
        TError,
        {clientId: string;data: UpdateDeviceDto},
        TContext
      > => {
      return useMutation(getPatchDeviceClientIdMutationOptions(options), queryClient);
    }
