/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticateDeviceDto,
  DeviceResponseDto,
  RegisterDeviceResponseDto,
  TokenPairExpiryDto,
  UpdateDeviceDto
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiDeviceRegisterResponse200 = {
  data: RegisterDeviceResponseDto
  status: 200
}

export type getApiDeviceRegisterResponseSuccess = (getApiDeviceRegisterResponse200) & {
  headers: Headers;
};
;

export type getApiDeviceRegisterResponse = (getApiDeviceRegisterResponseSuccess)

export const getGetApiDeviceRegisterUrl = () => {




  return `/api/device/register`
}

export const getApiDeviceRegister = async ( options?: RequestInit): Promise<getApiDeviceRegisterResponse> => {

  const res = await fetch(getGetApiDeviceRegisterUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiDeviceRegisterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDeviceRegisterResponse
}





export const getGetApiDeviceRegisterQueryKey = () => {
    return [
    `/api/device/register`
    ] as const;
    }


export const getGetApiDeviceRegisterQueryOptions = <TData = Awaited<ReturnType<typeof getApiDeviceRegister>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeviceRegister>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDeviceRegisterQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDeviceRegister>>> = ({ signal }) => getApiDeviceRegister({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiDeviceRegister>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDeviceRegisterQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDeviceRegister>>>
export type GetApiDeviceRegisterQueryError = unknown


export function useGetApiDeviceRegister<TData = Awaited<ReturnType<typeof getApiDeviceRegister>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeviceRegister>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDeviceRegister>>,
          TError,
          Awaited<ReturnType<typeof getApiDeviceRegister>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDeviceRegister<TData = Awaited<ReturnType<typeof getApiDeviceRegister>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeviceRegister>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDeviceRegister>>,
          TError,
          Awaited<ReturnType<typeof getApiDeviceRegister>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDeviceRegister<TData = Awaited<ReturnType<typeof getApiDeviceRegister>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeviceRegister>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiDeviceRegister<TData = Awaited<ReturnType<typeof getApiDeviceRegister>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeviceRegister>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDeviceRegisterQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postApiDeviceAuthenticateResponse200 = {
  data: TokenPairExpiryDto
  status: 200
}

export type postApiDeviceAuthenticateResponseSuccess = (postApiDeviceAuthenticateResponse200) & {
  headers: Headers;
};
;

export type postApiDeviceAuthenticateResponse = (postApiDeviceAuthenticateResponseSuccess)

export const getPostApiDeviceAuthenticateUrl = () => {




  return `/api/device/authenticate`
}

export const postApiDeviceAuthenticate = async (authenticateDeviceDto: AuthenticateDeviceDto, options?: RequestInit): Promise<postApiDeviceAuthenticateResponse> => {

  const res = await fetch(getPostApiDeviceAuthenticateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authenticateDeviceDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiDeviceAuthenticateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiDeviceAuthenticateResponse
}





export const getPostApiDeviceAuthenticateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiDeviceAuthenticate>>, TError,{data: AuthenticateDeviceDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiDeviceAuthenticate>>, TError,{data: AuthenticateDeviceDto}, TContext> => {

const mutationKey = ['postApiDeviceAuthenticate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiDeviceAuthenticate>>, {data: AuthenticateDeviceDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiDeviceAuthenticate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiDeviceAuthenticateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiDeviceAuthenticate>>>
    export type PostApiDeviceAuthenticateMutationBody = AuthenticateDeviceDto
    export type PostApiDeviceAuthenticateMutationError = unknown

    export const usePostApiDeviceAuthenticate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiDeviceAuthenticate>>, TError,{data: AuthenticateDeviceDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiDeviceAuthenticate>>,
        TError,
        {data: AuthenticateDeviceDto},
        TContext
      > => {
      return useMutation(getPostApiDeviceAuthenticateMutationOptions(options), queryClient);
    }
    export type getApiDeviceResponse200 = {
  data: DeviceResponseDto[]
  status: 200
}

export type getApiDeviceResponseSuccess = (getApiDeviceResponse200) & {
  headers: Headers;
};
;

export type getApiDeviceResponse = (getApiDeviceResponseSuccess)

export const getGetApiDeviceUrl = () => {




  return `/api/device`
}

export const getApiDevice = async ( options?: RequestInit): Promise<getApiDeviceResponse> => {

  const res = await fetch(getGetApiDeviceUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiDeviceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDeviceResponse
}





export const getGetApiDeviceQueryKey = () => {
    return [
    `/api/device`
    ] as const;
    }


export const getGetApiDeviceQueryOptions = <TData = Awaited<ReturnType<typeof getApiDevice>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDevice>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDeviceQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDevice>>> = ({ signal }) => getApiDevice({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiDevice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDeviceQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDevice>>>
export type GetApiDeviceQueryError = unknown


export function useGetApiDevice<TData = Awaited<ReturnType<typeof getApiDevice>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDevice>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDevice>>,
          TError,
          Awaited<ReturnType<typeof getApiDevice>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDevice<TData = Awaited<ReturnType<typeof getApiDevice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDevice>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDevice>>,
          TError,
          Awaited<ReturnType<typeof getApiDevice>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDevice<TData = Awaited<ReturnType<typeof getApiDevice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDevice>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiDevice<TData = Awaited<ReturnType<typeof getApiDevice>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDevice>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDeviceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteApiDeviceClientIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiDeviceClientIdResponseSuccess = (deleteApiDeviceClientIdResponse204) & {
  headers: Headers;
};
;

export type deleteApiDeviceClientIdResponse = (deleteApiDeviceClientIdResponseSuccess)

export const getDeleteApiDeviceClientIdUrl = (clientId: string,) => {




  return `/api/device/${clientId}`
}

export const deleteApiDeviceClientId = async (clientId: string, options?: RequestInit): Promise<deleteApiDeviceClientIdResponse> => {

  const res = await fetch(getDeleteApiDeviceClientIdUrl(clientId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiDeviceClientIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiDeviceClientIdResponse
}





export const getDeleteApiDeviceClientIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiDeviceClientId>>, TError,{clientId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiDeviceClientId>>, TError,{clientId: string}, TContext> => {

const mutationKey = ['deleteApiDeviceClientId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiDeviceClientId>>, {clientId: string}> = (props) => {
          const {clientId} = props ?? {};

          return  deleteApiDeviceClientId(clientId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiDeviceClientIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiDeviceClientId>>>

    export type DeleteApiDeviceClientIdMutationError = unknown

    export const useDeleteApiDeviceClientId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiDeviceClientId>>, TError,{clientId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiDeviceClientId>>,
        TError,
        {clientId: string},
        TContext
      > => {
      return useMutation(getDeleteApiDeviceClientIdMutationOptions(options), queryClient);
    }
    export type patchApiDeviceClientIdResponse204 = {
  data: void
  status: 204
}

export type patchApiDeviceClientIdResponseSuccess = (patchApiDeviceClientIdResponse204) & {
  headers: Headers;
};
;

export type patchApiDeviceClientIdResponse = (patchApiDeviceClientIdResponseSuccess)

export const getPatchApiDeviceClientIdUrl = (clientId: string,) => {




  return `/api/device/${clientId}`
}

export const patchApiDeviceClientId = async (clientId: string,
    updateDeviceDto: UpdateDeviceDto, options?: RequestInit): Promise<patchApiDeviceClientIdResponse> => {

  const res = await fetch(getPatchApiDeviceClientIdUrl(clientId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateDeviceDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchApiDeviceClientIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as patchApiDeviceClientIdResponse
}





export const getPatchApiDeviceClientIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiDeviceClientId>>, TError,{clientId: string;data: UpdateDeviceDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiDeviceClientId>>, TError,{clientId: string;data: UpdateDeviceDto}, TContext> => {

const mutationKey = ['patchApiDeviceClientId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiDeviceClientId>>, {clientId: string;data: UpdateDeviceDto}> = (props) => {
          const {clientId,data} = props ?? {};

          return  patchApiDeviceClientId(clientId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiDeviceClientIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiDeviceClientId>>>
    export type PatchApiDeviceClientIdMutationBody = UpdateDeviceDto
    export type PatchApiDeviceClientIdMutationError = unknown

    export const usePatchApiDeviceClientId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiDeviceClientId>>, TError,{clientId: string;data: UpdateDeviceDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiDeviceClientId>>,
        TError,
        {clientId: string;data: UpdateDeviceDto},
        TContext
      > => {
      return useMutation(getPatchApiDeviceClientIdMutationOptions(options), queryClient);
    }
