/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface BeatmapDifficultyDto {
  id: string;
  difficultyRank: string;
  difficultyName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  notesPerSecond: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  cuttableObjectCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  bombCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  obstacleCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  laneCount: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  noteJumpSpeed: number | string | null;
  characteristicSerializedName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  characteristicColorCount: number | string;
  characteristicRequires360Movement: boolean;
  characteristicContainsRotationEvents: boolean;
  createdAt: string;
}
