/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordDto {
  currentPassword: string;
  /** @minLength 4 */
  newPassword: string;
}
