/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { BeatmapDifficultyRank } from './beatmapDifficultyRank.ts';
import type { BeatSaverFetchStatus } from './beatSaverFetchStatus.ts';
import type { MapSortBy } from './mapSortBy.ts';
import type { SortDirection } from './sortDirection.ts';

export type GetApiMapsParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
PageSize?: number | string;
Search?: string;
Characteristic?: string;
Difficulty?: BeatmapDifficultyRank;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MinBpm?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MaxBpm?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
MinDurationSeconds?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
MaxDurationSeconds?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MinNps?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MaxNps?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MinDifficulty?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MaxDifficulty?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MinPp?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MaxPp?: number | string;
Ranked?: boolean;
Automapper?: boolean;
Tag?: string;
FetchStatus?: BeatSaverFetchStatus;
Played?: boolean;
Liked?: boolean;
SortBy?: MapSortBy;
SortDir?: SortDirection;
};
