/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { BeatmapDifficultyRank } from './beatmapDifficultyRank.ts';
import type { SessionSortBy } from './sessionSortBy.ts';
import type { SortDirection } from './sortDirection.ts';

export type GetApiSessionsParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
PageSize?: number | string;
Search?: string;
Difficulty?: BeatmapDifficultyRank;
From?: string;
To?: string;
BeatmapId?: string;
SortBy?: SessionSortBy;
SortDir?: SortDirection;
IncludeAuto?: boolean;
IncludeFailed?: boolean;
IncludeQuit?: boolean;
IncludeIncomplete?: boolean;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MinAccuracy?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MaxAccuracy?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
MinScore?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
MaxScore?: number | string;
Rank?: string;
FullComboOnly?: boolean;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MinBpm?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
MaxBpm?: number | string;
};
