/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SittingSortBy } from './sittingSortBy.ts';

export type GetSittingsParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
sortBy?: SittingSortBy;
};
