/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface GridCellDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  hand: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  lineIndex: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  noteLineLayer: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  accuracy: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  missRate: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  count: number | string;
}
