/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface HeartRateSampleDto {
  recordedAt: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  bpm: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  caloriesKcal: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  steps: number | string | null;
  /** @nullable */
  source: string | null;
}
