/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface HspSampleDto {
  metric: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  value: number | string;
  /** @nullable */
  unit: string | null;
  recordedAt: string;
  /** @nullable */
  source: string | null;
}
