/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MapBeatSaverDetailDto {
  beatSaverId: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  uploader: string | null;
  ranked: boolean;
  qualified: boolean;
  automapper: boolean;
  /** @nullable */
  uploaded: string | null;
  tags: string[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  plays: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  downloads: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  upvotes: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  downvotes: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  score: number | string;
}
