/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MapBeatSaverSummaryDto {
  ranked: boolean;
  automapper: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  downloads: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  upvotes: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  score: number | string;
  tags: string[];
}
