/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { BeatmapDifficultyDto } from './beatmapDifficultyDto.ts';
import type { MapBeatSaverDetailDto } from './mapBeatSaverDetailDto.ts';

export interface MapDetailDto {
  id: string;
  levelId: string;
  songName: string;
  /** @nullable */
  songSubName: string | null;
  songAuthor: string;
  mapper: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  bpm: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  durationMs: number | string;
  /** @nullable */
  coverImageKey: string | null;
  fetchStatus: string;
  /** @nullable */
  fetchLastAttemptedAt: string | null;
  /** @nullable */
  fetchError: string | null;
  createdAt: string;
  updatedAt: string;
  beatSaver: null | MapBeatSaverDetailDto;
  difficulties: BeatmapDifficultyDto[];
}
