/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MapDifficultyAnalysisDtoCharacteristics } from './mapDifficultyAnalysisDtoCharacteristics.ts';

export interface MapDifficultyAnalysisDto {
  status: string;
  featureStatus: string;
  metricStatus: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  difficultyRating: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  pp: number | string | null;
  /** @nullable */
  characteristics: MapDifficultyAnalysisDtoCharacteristics;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  noteCount: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  bombCount: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  obstacleCount: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  chainCount: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  arcCount: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  njs: number | string | null;
  /** @nullable */
  formatVersion: string | null;
  analyzedAt: string;
}
