/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MapListItemDto } from './mapListItemDto.ts';

export interface MapListDetailDto {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  createdAt: string;
  updatedAt: string;
  maps: MapListItemDto[];
}
