/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MapListSummaryDto {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  mapCount: number | string;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  containsMap: boolean | null;
  coverMapIds: string[];
}
