/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MetricConfigCharacteristics } from './metricConfigCharacteristics.ts';
import type { PpConfig } from './ppConfig.ts';
import type { WeightedModel } from './weightedModel.ts';

export interface MetricConfig {
  difficulty?: WeightedModel;
  pp?: PpConfig;
  characteristics?: MetricConfigCharacteristics;
}
