/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { WeightedModel } from './weightedModel.ts';

export type MetricConfigCharacteristics = {[key: string]: WeightedModel};
