/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { FeatureCatalogItemDto } from './featureCatalogItemDto.ts';
import type { MetricConfig } from './metricConfig.ts';

export interface MetricConfigResponse {
  config: MetricConfig;
  features: FeatureCatalogItemDto[];
}
