/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface NoteItemDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  songTimeMs: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  colorType: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  noteType: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  scoringType: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  cutDirection: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  lineIndex: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  noteLineLayer: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  result: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxScore: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  beforeCutScore: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  centerDistanceScore: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  afterCutScore: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  preCutSwing: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  postCutSwing: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  cutPointDistance: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  saberSpeed: number | string;
}
