/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PersonalBestDto {
  sessionId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  score: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  accuracy: number | string;
  rank: string;
}
