/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { BeatmapInfoDto } from './beatmapInfoDto.ts';
import type { PlaySessionResultsDto } from './playSessionResultsDto.ts';

export interface PlaySessionDetailDto {
  id: string;
  startedAt: string;
  /** @nullable */
  endedAt: string | null;
  /**
     * @nullable
     * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
     */
  duration: string | null;
  beatmap: BeatmapInfoDto;
  autoMode: boolean;
  /** @nullable */
  endReason: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  modifierFlags: number | string | null;
  results: null | PlaySessionResultsDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  noteCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  comboBreakCount: number | string;
  hasMotionData: boolean;
}
