/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PlaySessionResultsDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  score: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxPossibleScore: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  accuracy: number | string;
  rank: string;
  fullCombo: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxCombo: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  goodCuts: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  badCuts: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  misses: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  finalEnergy: number | string;
}
