/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PlaySessionResultsDto } from './playSessionResultsDto.ts';

export interface PlaySessionListItemDto {
  id: string;
  startedAt: string;
  /** @nullable */
  endedAt: string | null;
  /**
     * @nullable
     * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
     */
  duration: string | null;
  beatmapId: string;
  songName: string;
  /** @nullable */
  songSubName: string | null;
  songAuthor: string;
  mapper: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  bpm: number | string;
  difficultyRank: string;
  difficultyName: string;
  autoMode: boolean;
  /** @nullable */
  endReason: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  modifierFlags: number | string | null;
  results: null | PlaySessionResultsDto;
}
