/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PracticeRecommendationDto {
  beatmapId: string;
  beatmapDifficultyId: string;
  songName: string;
  songAuthor: string;
  mapper: string;
  difficultyRank: string;
  difficultyName: string;
  characteristicSerializedName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  difficultyRating: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  matchScore: number | string;
  targetedCharacteristics: string[];
}
