/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityDayDto } from './activityDayDto.ts';
import type { PublicProfileHistoryDto } from './publicProfileHistoryDto.ts';
import type { PublicProfileStatsDto } from './publicProfileStatsDto.ts';
import type { SkillProfileDto } from './skillProfileDto.ts';

export interface PublicProfileDto {
  handle: string;
  displayName: string;
  stats: null | PublicProfileStatsDto;
  /** @nullable */
  activity: ActivityDayDto[] | null;
  skill: null | SkillProfileDto;
  history: null | PublicProfileHistoryDto;
}
