/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MostPlayedMapDto } from './mostPlayedMapDto.ts';
import type { RankCountDto } from './rankCountDto.ts';

export interface PublicProfileStatsDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPlays: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPlayTimeMs: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  averageAccuracy: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  fullCombos: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  uniqueMaps: number | string;
  rankDistribution: RankCountDto[];
  mostPlayedMaps: MostPlayedMapDto[];
}
