/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RecapDeltaDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  scoreDelta: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  accuracyDelta: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxComboDelta: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  missesDelta: number | string;
}
