/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RefreshTokenRequestDto {
  clientId: string;
  accessToken: string;
  refreshToken: string;
}
