/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterDto {
  /** @maxLength 32 */
  displayName: string;
  /** @maxLength 32 */
  userName: string;
  email: string;
  /** @minLength 4 */
  password: string;
}
