/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PlaySessionDetailDto } from './playSessionDetailDto.ts';
import type { PlaySessionResultsDto } from './playSessionResultsDto.ts';
import type { RecapDeltaDto } from './recapDeltaDto.ts';

export interface SessionRecapDto {
  session: PlaySessionDetailDto;
  previousAttempt: null | PlaySessionResultsDto;
  personalBest: null | PlaySessionResultsDto;
  vsPrevious: RecapDeltaDto;
  vsAverage: RecapDeltaDto;
  isNewPersonalBest: boolean;
}
