/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SittingsOverviewDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalSessions: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPlays: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalActiveMs: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  avgPlaysPerSession: number | string;
  /** @nullable */
  lastPlayedAt: string | null;
}
