/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from './iFormFile.ts';

export type UploadBannerBody = {
  file: IFormFile;
};
