// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shiron.BeatDash.DB;

#nullable disable

namespace Shiron.BeatDash.DB.Migrations
{
    [DbContext(typeof(BeatDashDbContext))]
    [Migration("20260704080218_AddPlaySessionMotionFrameItems")]
    partial class AddPlaySessionMotionFrameItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.Beatmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Bpm")
                        .HasColumnType("real");

                    b.Property<string>("CoverImageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Mapper")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SongAuthor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SongSubName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LevelId")
                        .IsUnique();

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("Beatmaps", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.BeatmapDifficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeatmapId")
                        .HasColumnType("uuid");

                    b.Property<int>("BombCount")
                        .HasColumnType("integer");

                    b.Property<int>("CharacteristicColorCount")
                        .HasColumnType("integer");

                    b.Property<bool>("CharacteristicContainsRotationEvents")
                        .HasColumnType("boolean");

                    b.Property<bool>("CharacteristicRequires360Movement")
                        .HasColumnType("boolean");

                    b.Property<string>("CharacteristicSerializedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CuttableObjectCount")
                        .HasColumnType("integer");

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DifficultyRank")
                        .HasColumnType("integer");

                    b.Property<int>("LaneCount")
                        .HasColumnType("integer");

                    b.Property<float?>("NoteJumpSpeed")
                        .HasColumnType("real");

                    b.Property<float>("NotesPerSecond")
                        .HasColumnType("real");

                    b.Property<int>("ObstacleCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("BeatmapId", "CharacteristicSerializedName", "DifficultyRank")
                        .IsUnique();

                    b.ToTable("BeatmapDifficulties", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClientId", "UserId")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeatmapDifficultyId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrelationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapDifficultyId");

                    b.HasIndex("UserId");

                    b.ToTable("PlaySessions", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrelationId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlaySessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SongTimeMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlaySessionId", "SongTimeMs");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionComboBreakItem", b =>
                {
                    b.HasBaseType("Shiron.BeatDash.DB.Schema.PlaySessionItem");

                    b.Property<int>("ComboBefore")
                        .HasColumnType("integer");

                    b.ToTable("PlaySessionComboBreakItems", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionEnergyChangeItem", b =>
                {
                    b.HasBaseType("Shiron.BeatDash.DB.Schema.PlaySessionItem");

                    b.Property<float>("EnergyBefore")
                        .HasColumnType("real");

                    b.ToTable("PlaySessionEnergyChangeItems", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionItemMotionFrame", b =>
                {
                    b.HasBaseType("Shiron.BeatDash.DB.Schema.PlaySessionItem");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("FrameCount")
                        .HasColumnType("integer");

                    b.ToTable("PlaySessionItemMotionFrames", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionNoteItem", b =>
                {
                    b.HasBaseType("Shiron.BeatDash.DB.Schema.PlaySessionItem");

                    b.Property<int>("ColorType")
                        .HasColumnType("integer");

                    b.Property<int>("CutDirection")
                        .HasColumnType("integer");

                    b.Property<float>("CutPointDistance")
                        .HasColumnType("real");

                    b.Property<int>("LineIndex")
                        .HasColumnType("integer");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("NoteLineLayer")
                        .HasColumnType("integer");

                    b.Property<int>("NoteType")
                        .HasColumnType("integer");

                    b.Property<float>("PostCutSwing")
                        .HasColumnType("real");

                    b.Property<float>("PreCutSwing")
                        .HasColumnType("real");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<float>("SaberSpeed")
                        .HasColumnType("real");

                    b.ToTable("PlaySessionNoteItems", (string)null);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionScoreChangeItem", b =>
                {
                    b.HasBaseType("Shiron.BeatDash.DB.Schema.PlaySessionItem");

                    b.Property<int>("ScoreBefore")
                        .HasColumnType("integer");

                    b.ToTable("PlaySessionScoreChangeItems", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiron.BeatDash.DB.Schema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.Beatmap", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.BeatmapDifficulty", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.Beatmap", "Beatmap")
                        .WithMany("Difficulties")
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiron.BeatDash.DB.Schema.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Beatmap");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.Device", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySession", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.BeatmapDifficulty", "BeatmapDifficulty")
                        .WithMany()
                        .HasForeignKey("BeatmapDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiron.BeatDash.DB.Schema.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeatmapDifficulty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.RefreshToken", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.Device", "Device")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionComboBreakItem", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.PlaySession", "PlaySession")
                        .WithMany("ComboBreakItems")
                        .HasForeignKey("PlaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaySession");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionEnergyChangeItem", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.PlaySession", "PlaySession")
                        .WithMany("EnergyChangeItems")
                        .HasForeignKey("PlaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaySession");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionItemMotionFrame", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.PlaySession", "PlaySession")
                        .WithMany("MotionFrameItems")
                        .HasForeignKey("PlaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaySession");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionNoteItem", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.PlaySession", "PlaySession")
                        .WithMany("NoteItems")
                        .HasForeignKey("PlaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaySession");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySessionScoreChangeItem", b =>
                {
                    b.HasOne("Shiron.BeatDash.DB.Schema.PlaySession", "PlaySession")
                        .WithMany("ScoreChangeItems")
                        .HasForeignKey("PlaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaySession");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.Beatmap", b =>
                {
                    b.Navigation("Difficulties");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.Device", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.PlaySession", b =>
                {
                    b.Navigation("ComboBreakItems");

                    b.Navigation("EnergyChangeItems");

                    b.Navigation("MotionFrameItems");

                    b.Navigation("NoteItems");

                    b.Navigation("ScoreChangeItems");
                });

            modelBuilder.Entity("Shiron.BeatDash.DB.Schema.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
