/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Shiron.BeatDash.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AnonymousTypeOfstring,
  GetHeartRateCurveParams,
  HealthOverviewDto,
  HeartRatePointDto,
  WorkoutDto
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiHealthResponse200 = {
  data: AnonymousTypeOfstring
  status: 200
}

export type getApiHealthResponseSuccess = (getApiHealthResponse200) & {
  headers: Headers;
};
;

export type getApiHealthResponse = (getApiHealthResponseSuccess)

export const getGetApiHealthUrl = () => {




  return `/api/health`
}

export const getApiHealth = async ( options?: RequestInit): Promise<getApiHealthResponse> => {

  const res = await fetch(getGetApiHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiHealthResponse
}





export const getGetApiHealthQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }


export const getGetApiHealthQueryOptions = <TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiHealth>>> = ({ signal }) => getApiHealth({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiHealth>>>
export type GetApiHealthQueryError = unknown


export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getHealthOverviewResponse200 = {
  data: HealthOverviewDto
  status: 200
}

export type getHealthOverviewResponse204 = {
  data: void
  status: 204
}

export type getHealthOverviewResponse401 = {
  data: void
  status: 401
}

export type getHealthOverviewResponseSuccess = (getHealthOverviewResponse200 | getHealthOverviewResponse204) & {
  headers: Headers;
};
export type getHealthOverviewResponseError = (getHealthOverviewResponse401) & {
  headers: Headers;
};

export type getHealthOverviewResponse = (getHealthOverviewResponseSuccess | getHealthOverviewResponseError)

export const getGetHealthOverviewUrl = () => {




  return `/api/health/overview`
}

/**
 * The current user's fitness overview (calories, active time, trends, body context).
 */
export const getHealthOverview = async ( options?: RequestInit): Promise<getHealthOverviewResponse> => {

  const res = await fetch(getGetHealthOverviewUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHealthOverviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getHealthOverviewResponse
}





export const getGetHealthOverviewQueryKey = () => {
    return [
    `/api/health/overview`
    ] as const;
    }


export const getGetHealthOverviewQueryOptions = <TData = Awaited<ReturnType<typeof getHealthOverview>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthOverview>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthOverviewQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthOverview>>> = ({ signal }) => getHealthOverview({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealthOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof getHealthOverview>>>
export type GetHealthOverviewQueryError = void


export function useGetHealthOverview<TData = Awaited<ReturnType<typeof getHealthOverview>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthOverview>>,
          TError,
          Awaited<ReturnType<typeof getHealthOverview>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealthOverview<TData = Awaited<ReturnType<typeof getHealthOverview>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthOverview>>,
          TError,
          Awaited<ReturnType<typeof getHealthOverview>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealthOverview<TData = Awaited<ReturnType<typeof getHealthOverview>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthOverview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHealthOverview<TData = Awaited<ReturnType<typeof getHealthOverview>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthOverview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthOverviewQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getSessionWorkoutResponse200 = {
  data: WorkoutDto
  status: 200
}

export type getSessionWorkoutResponse401 = {
  data: void
  status: 401
}

export type getSessionWorkoutResponse404 = {
  data: void
  status: 404
}

export type getSessionWorkoutResponseSuccess = (getSessionWorkoutResponse200) & {
  headers: Headers;
};
export type getSessionWorkoutResponseError = (getSessionWorkoutResponse401 | getSessionWorkoutResponse404) & {
  headers: Headers;
};

export type getSessionWorkoutResponse = (getSessionWorkoutResponseSuccess | getSessionWorkoutResponseError)

export const getGetSessionWorkoutUrl = (sessionId: string,) => {




  return `/api/sessions/${sessionId}/workout`
}

/**
 * Per-play workout figures (calories, active time, intensity, movement, heart rate).
 */
export const getSessionWorkout = async (sessionId: string, options?: RequestInit): Promise<getSessionWorkoutResponse> => {

  const res = await fetch(getGetSessionWorkoutUrl(sessionId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSessionWorkoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSessionWorkoutResponse
}





export const getGetSessionWorkoutQueryKey = (sessionId: string,) => {
    return [
    `/api/sessions/${sessionId}/workout`
    ] as const;
    }


export const getGetSessionWorkoutQueryOptions = <TData = Awaited<ReturnType<typeof getSessionWorkout>>, TError = void>(sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionWorkout>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionWorkoutQueryKey(sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessionWorkout>>> = ({ signal }) => getSessionWorkout(sessionId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: sessionId !== null && sessionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSessionWorkout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSessionWorkoutQueryResult = NonNullable<Awaited<ReturnType<typeof getSessionWorkout>>>
export type GetSessionWorkoutQueryError = void


export function useGetSessionWorkout<TData = Awaited<ReturnType<typeof getSessionWorkout>>, TError = void>(
 sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionWorkout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionWorkout>>,
          TError,
          Awaited<ReturnType<typeof getSessionWorkout>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSessionWorkout<TData = Awaited<ReturnType<typeof getSessionWorkout>>, TError = void>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionWorkout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionWorkout>>,
          TError,
          Awaited<ReturnType<typeof getSessionWorkout>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSessionWorkout<TData = Awaited<ReturnType<typeof getSessionWorkout>>, TError = void>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionWorkout>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSessionWorkout<TData = Awaited<ReturnType<typeof getSessionWorkout>>, TError = void>(
 sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionWorkout>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSessionWorkoutQueryOptions(sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getHeartRateCurveResponse200 = {
  data: HeartRatePointDto[]
  status: 200
}

export type getHeartRateCurveResponse204 = {
  data: void
  status: 204
}

export type getHeartRateCurveResponse401 = {
  data: void
  status: 401
}

export type getHeartRateCurveResponseSuccess = (getHeartRateCurveResponse200 | getHeartRateCurveResponse204) & {
  headers: Headers;
};
export type getHeartRateCurveResponseError = (getHeartRateCurveResponse401) & {
  headers: Headers;
};

export type getHeartRateCurveResponse = (getHeartRateCurveResponseSuccess | getHeartRateCurveResponseError)

export const getGetHeartRateCurveUrl = (params: GetHeartRateCurveParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/health/heartrate?${stringifiedParams}` : `/api/health/heartrate`
}

/**
 * Heart-rate curve over a time window (e.g. a whole sitting), relative to 'from'.
 */
export const getHeartRateCurve = async (params: GetHeartRateCurveParams, options?: RequestInit): Promise<getHeartRateCurveResponse> => {

  const res = await fetch(getGetHeartRateCurveUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHeartRateCurveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getHeartRateCurveResponse
}





export const getGetHeartRateCurveQueryKey = (params?: GetHeartRateCurveParams,) => {
    return [
    `/api/health/heartrate`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetHeartRateCurveQueryOptions = <TData = Awaited<ReturnType<typeof getHeartRateCurve>>, TError = void>(params: GetHeartRateCurveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartRateCurve>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHeartRateCurveQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHeartRateCurve>>> = ({ signal }) => getHeartRateCurve(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHeartRateCurve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHeartRateCurveQueryResult = NonNullable<Awaited<ReturnType<typeof getHeartRateCurve>>>
export type GetHeartRateCurveQueryError = void


export function useGetHeartRateCurve<TData = Awaited<ReturnType<typeof getHeartRateCurve>>, TError = void>(
 params: GetHeartRateCurveParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartRateCurve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeartRateCurve>>,
          TError,
          Awaited<ReturnType<typeof getHeartRateCurve>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHeartRateCurve<TData = Awaited<ReturnType<typeof getHeartRateCurve>>, TError = void>(
 params: GetHeartRateCurveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartRateCurve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHeartRateCurve>>,
          TError,
          Awaited<ReturnType<typeof getHeartRateCurve>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHeartRateCurve<TData = Awaited<ReturnType<typeof getHeartRateCurve>>, TError = void>(
 params: GetHeartRateCurveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartRateCurve>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHeartRateCurve<TData = Awaited<ReturnType<typeof getHeartRateCurve>>, TError = void>(
 params: GetHeartRateCurveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHeartRateCurve>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHeartRateCurveQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






